# Exercise the actual configure-time boundary, including source/patch drift.
set(_fixture "${BINARY_DIR}/eui-ime-patch-test")
file(REMOVE_RECURSE "${_fixture}")
file(MAKE_DIRECTORY "${_fixture}/third_party/EUI-NEO/3rd/glfw/src"
    "${_fixture}/docs/eui_neo_feedback/patches")
set(_source "third_party/EUI-NEO/3rd/glfw/src/x11_window.c")
set(_patch "docs/eui_neo_feedback/patches/EUI-20261001-002-filtered-x11-keys.patch")
configure_file("${SOURCE_DIR}/third_party/dependencies.lock.json"
    "${_fixture}/third_party/dependencies.lock.json" COPYONLY)
configure_file("${SOURCE_DIR}/${_source}" "${_fixture}/${_source}" COPYONLY)
configure_file("${SOURCE_DIR}/${_patch}" "${_fixture}/${_patch}" COPYONLY)
set(_project [=[
cmake_minimum_required(VERSION 3.25)
project(ime_patch_fixture LANGUAGES C)
find_package(Git REQUIRED)
set(GLFW_BUILD_X11 ON)
add_library(glfw STATIC "${PROJECT_SOURCE_DIR}/third_party/EUI-NEO/3rd/glfw/src/x11_window.c")
include("@SOURCE_DIR@/cmake/EuiX11ImePatch.cmake")
aki_apply_eui_x11_ime_patch()
get_target_property(_sources glfw SOURCES)
if(NOT _sources STREQUAL "${PROJECT_BINARY_DIR}/compat/eui-x11-ime/3rd/glfw/src/x11_window.c")
    message(FATAL_ERROR "GLFW does not compile the generated source")
endif()
]=])
string(CONFIGURE "${_project}" _project @ONLY)
file(WRITE "${_fixture}/CMakeLists.txt" "${_project}")
function(configure_fixture expect_success error_text)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${_fixture}" -B "${_fixture}/build"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    if(expect_success)
        if(NOT _result EQUAL 0)
            message(FATAL_ERROR "Patch fixture configure failed: ${_out}${_err}")
        endif()
    elseif(_result EQUAL 0 OR NOT "${_out}${_err}" MATCHES "${error_text}")
        message(FATAL_ERROR "Patch drift was not rejected: ${_out}${_err}")
    endif()
endfunction()
configure_fixture(TRUE "")
configure_fixture(TRUE "") # idempotent reconfigure, not double-application
file(SHA256 "${SOURCE_DIR}/${_source}" _original)
file(SHA256 "${_fixture}/${_source}" _retained)
if(NOT _original STREQUAL _retained)
    message(FATAL_ERROR "The pinned input source was modified")
endif()
file(APPEND "${_fixture}/${_patch}" "\n# drift\n")
configure_fixture(FALSE "source or patch hash mismatch")
configure_file("${SOURCE_DIR}/${_patch}" "${_fixture}/${_patch}" COPYONLY)
file(APPEND "${_fixture}/${_source}" "\n/* drift */\n")
configure_fixture(FALSE "source or patch hash mismatch")
configure_file("${SOURCE_DIR}/${_source}" "${_fixture}/${_source}" COPYONLY)
configure_fixture(TRUE "")
file(REMOVE_RECURSE "${_fixture}")
