# EUI-20261001-002. The maintainer authorized this temporary build override.
# Apply to a generated copy; the pinned checkout and commit remain unchanged.
function(aki_apply_eui_x11_ime_patch)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR NOT GLFW_BUILD_X11)
        return()
    endif()
    file(READ "${PROJECT_SOURCE_DIR}/third_party/dependencies.lock.json" _lock)
    string(JSON _count LENGTH "${_lock}" dependencies)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE ${_last})
        string(JSON _name GET "${_lock}" dependencies ${_index} name)
        if(_name STREQUAL "EUI-NEO")
            string(JSON _entry GET "${_lock}" dependencies ${_index} local_patches 0)
        endif()
    endforeach()
    if(NOT DEFINED _entry)
        message(FATAL_ERROR "EUI-20261001-002 patch manifest missing")
    endif()
    string(JSON _patch GET "${_entry}" path)
    string(JSON _patch_hash GET "${_entry}" sha256)
    string(JSON _source GET "${_entry}" source)
    string(JSON _source_hash GET "${_entry}" source_sha256)
    string(JSON _output_hash GET "${_entry}" patched_sha256)
    set(_original "${PROJECT_SOURCE_DIR}/third_party/EUI-NEO/${_source}")
    set(_patch "${PROJECT_SOURCE_DIR}/${_patch}")
    file(SHA256 "${_original}" _actual_source)
    file(SHA256 "${_patch}" _actual_patch)
    if(NOT _actual_source STREQUAL _source_hash OR NOT _actual_patch STREQUAL _patch_hash)
        message(FATAL_ERROR "EUI-20261001-002 source or patch hash mismatch; review the dependency upgrade")
    endif()
    set(_copy_root "${PROJECT_BINARY_DIR}/compat/eui-x11-ime")
    set(_copy "${_copy_root}/${_source}")
    get_filename_component(_copy_dir "${_copy}" DIRECTORY)
    file(MAKE_DIRECTORY "${_copy_dir}")
    configure_file("${_original}" "${_copy}" COPYONLY)
    execute_process(COMMAND "${GIT_EXECUTABLE}" apply --whitespace=error-all "${_patch}"
        WORKING_DIRECTORY "${_copy_root}" RESULT_VARIABLE _apply_result
        ERROR_VARIABLE _apply_error)
    if(NOT _apply_result EQUAL 0)
        message(FATAL_ERROR "EUI-20261001-002 patch failed: ${_apply_error}")
    endif()
    file(SHA256 "${_copy}" _actual_output)
    if(NOT _actual_output STREQUAL _output_hash)
        message(FATAL_ERROR "EUI-20261001-002 generated source hash mismatch")
    endif()
    get_target_property(_sources glfw SOURCES)
    get_target_property(_source_dir glfw SOURCE_DIR)
    get_target_property(_binary_dir glfw BINARY_DIR)
    set(_replacement_count 0)
    set(_patched_sources)
    foreach(_file IN LISTS _sources)
        if(NOT IS_ABSOLUTE "${_file}" AND NOT _file MATCHES "^\\$<")
            # GLFW's Wayland protocol files are generated in its binary
            # directory. Retain their location when normalizing target sources.
            get_source_file_property(_generated "${_binary_dir}/${_file}"
                DIRECTORY "${_source_dir}" GENERATED)
            if(_generated)
                set(_file "${_binary_dir}/${_file}")
            else()
                set(_file "${_source_dir}/${_file}")
            endif()
        endif()
        if(_file STREQUAL _original)
            set(_file "${_copy}")
            math(EXPR _replacement_count "${_replacement_count} + 1")
        endif()
        list(APPEND _patched_sources "${_file}")
    endforeach()
    if(NOT _replacement_count EQUAL 1)
        message(FATAL_ERROR "EUI-20261001-002 expected exactly one GLFW X11 window source")
    endif()
    set_property(TARGET glfw PROPERTY SOURCES "${_patched_sources}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_patch}" "${_original}")
    message(STATUS "EUI-20261001-002 applied to generated GLFW source (${_actual_output})")
endfunction()
